// Generated by CoffeeScript 1.4.0
(function() {
  var Player;

  Player = (function() {

    Player.prototype.id = void 0;

    function Player(x, y) {
      this.x = x;
      this.y = y;
    }

    return Player;

  })();

  exports.Player = Player;

}).call(this);
